Repository WannaReact/gugu-survive, pull requests merged in 2022-01, with the labels that each got.

#3 webpack 세팅
  package-lock.json
  package.json
  src/assets/images/meat.png
  webpack.config.js
Labels: 세팅

#4 express 세팅
  .eslintrc.js
  package-lock.json
  package.json
  server.js
  webpack.config.js
Labels: 세팅

#8 mongoDB 연결
  .eslintrc.js
  .gitignore
  package-lock.json
  package.json
  routes/addRecord.js
  routes/leaderboard.js
  schemas/record.js
  server.js
Labels: 기능 추가, 세팅

#10 [Feature/buttons] utilButtons에 onClick 추가
  package-lock.json
  src/components/buttons/UtilButton.jsx
Labels: 기능 추가

#15 [Feature/buttons] UtilButtons 와 NumPadButtons 변경 및 body에 스타일 적용
  src/components/buttons/NumPadButtons.jsx
  src/components/buttons/UtilButton.jsx
  src/pages/Home.jsx
  src/styles/reset.css
Labels: 기능 추가

#17 [Feature/buttons] UtilButton과 NumPadButton 하나의 컴포넌트로 통합
  src/components/Button.jsx
  src/components/buttons/NumPadButtons.jsx
  src/components/buttons/UtilButton.jsx
  src/constants/spec.js
  src/pages/Home.jsx
Labels: 기능 추가

#18 Game 페이지 progress bar 구현
  src/App.jsx
  src/components/game/GameKeyPad.jsx
  src/components/game/GameTimer.jsx
  src/pages/Game.jsx
Labels: 기능 추가

#22 순위표 정렬 기능 추가
  routes/leaderboard.js
  src/components/leaderboard/Cell.jsx
  src/components/leaderboard/HomeButton.jsx
  src/components/leaderboard/Record.jsx
  src/components/leaderboard/Table.jsx
  src/pages/Leaderboard.jsx
Labels: 기능 추가

#24 [Feature/router] router 및 modal 추가
  public/index.html
  src/App.jsx
  src/components/Portal.js
  src/components/Router.jsx
  src/components/modal/CloseButton.jsx
  src/components/modal/Modal.jsx
  src/components/modal/ModalContent.jsx
  src/pages/Home.jsx
  src/pages/Leaderboard.jsx
Labels: 기능 추가

#25 Game 페이지 UI 구현 및 GameKeyPad 컴포넌트 구현
  src/components/game/GameKeyPad.jsx
  src/components/game/GameTimer.jsx
  src/constants/spec.js
  src/pages/Game.jsx
Labels: 기능 추가

#28 GameTimer 수정
  .eslintrc.js
  src/components/game/GameTimer.jsx
  src/pages/Game.jsx
Labels: 버그 수정

#29 Modal 기능 구현
  src/components/modal/ExplainModalContent.jsx
  src/components/modal/RegisterModalContent.jsx
  src/components/modal/ResultModalContent.jsx
  src/constants/modal-spec.js
Labels: 기능 추가

#31 Home에서 Modal 연결 완료
  src/components/modal/ExplainModalContent.jsx
  src/components/modal/Modal.jsx
  src/components/modal/ModalContent.jsx
  src/components/modal/RegisterModalContent.jsx
  src/components/modal/ResultModalContent.jsx
  src/constants/modal-spec.js
  src/pages/Home.jsx
Labels: 기능 추가

#32 Game 페이지 gamelogic 기능 추가
  src/components/game/GameKeyPad.jsx
  src/components/modal/Modal.jsx
  src/pages/Game.jsx
  src/pages/Home.jsx
Labels: 기능 추가

#34 Feature/fix game logic
  src/components/game/GameTimer.jsx
  src/pages/Game.jsx
Labels: 버그 수정, 기능 추가

#36 모달 개선 및 CSS 추가
  src/components/Title.jsx
  src/components/modal/ExplainModalContent.jsx
  src/components/modal/Modal.jsx
  src/components/modal/ResultModalContent.jsx
  src/constants/color.js
  src/constants/modal-spec.js
  src/constants/spec.js
  src/pages/Home.jsx
Labels: 버그 수정, 기능 추가

#37 키패드를 누를 때 불필요한 리렌더링이 일어나지 않도록 성능 개선
  src/components/Button.jsx
  src/components/game/GameInfo.jsx
  src/components/game/GameTimer.jsx
  src/components/game/Problem.jsx
  src/pages/Game.jsx
Labels: 버그 수정

#41 Game over modal 출력 및 modal창으로 score props 이동
  src/components/game/GameTimer.jsx
  src/components/modal/ResultModalContent.jsx
  src/pages/Game.jsx
Labels: 기능 추가

#40 타이머 UI 변경
  src/components/game/GameTimer.jsx
Labels: 기능 추가

#45 Feature/notfound 404 Error Page 추가
  src/assets/images/gugu404.png
  src/pages/Notfound.jsx
Labels: 기능 추가

#43 Game 페이지 UI 및 버그 수정
  .eslintrc.js
  src/components/game/GameTimer.jsx
  src/pages/Game.jsx
  src/pages/Home.jsx
Labels: 버그 수정, 기능 추가

#47 [Feature/modal] RegisterInput Validation 버그 수정
  src/components/Button.jsx
  src/components/modal/ConfirmButton.jsx
  src/components/modal/RegisterInput.jsx
  src/components/modal/RegisterModalContent.jsx
Labels: 버그 수정

#49 Game 페이지 useReducer변경 리팩토링 및 최적화
  src/components/game/GameKeyPad.jsx
  src/components/modal/ResultModalContent.jsx
  src/pages/Game.jsx
Labels: 기능 추가

#50 heroku 배포를 위한 package.json 변경
  package-lock.json
  package.json
Labels: 세팅

#51 Home 페이지, Game 페이지 수정
  src/components/modal/ConfirmButton.jsx
  src/components/modal/ExplainModalContent.jsx
  src/components/modal/RegisterInput.jsx
  src/components/modal/RegisterModalContent.jsx
  src/components/modal/ResultModalContent.jsx
  src/pages/Game.jsx
Labels: 버그 수정, 기능 추가

#52 API 변경
  routes/addRecord.js
  routes/record.js
  server.js
  src/components/leaderboard/Table.jsx
  src/pages/Game.jsx
Labels: 기능 추가, 세팅

#53 spinner 추가
  src/components/leaderboard/Table.jsx
Labels: 기능 추가

#55 react-helmet-async로 각 페이지별 title 태그 설정
  build/asset-manifest.json
  build/index.html
  build/og.png
  build/static/js/main.0ac5b20c.js.map
  build/static/js/main.5a3fb82d.js
  build/static/js/main.5a3fb82d.js.LICENSE.txt
  build/static/js/main.5a3fb82d.js.map
  public/index.html
  public/og.png
  src/index.jsx
  src/pages/Game.jsx
  src/pages/Leaderboard.jsx
Labels: 기능 추가

#57 Feature/fix leaderboard
  src/components/leaderboard/Cell.jsx
  src/components/leaderboard/Record.jsx
  src/components/leaderboard/Table.jsx
Labels: 버그 수정

#58 버튼에 hover 효과 추가
  src/components/Button.jsx
Labels: 기능 추가
